Repository JuliaGeometry/MeshIntegrals.jl, pull requests merged in 2024-12, with the labels that each got.

#147 Rename _default_method and absorb _gausslegendre
  src/differentiation.jl
  src/integral.jl
  src/utils.jl
  test/combinations.jl
  test/utils.jl
Labels: refactoring

#150 Unify spelling of "parametrize"
  src/specializations/BezierCurve.jl
  src/specializations/ConeSurface.jl
  src/specializations/CylinderSurface.jl
  src/specializations/FrustumSurface.jl
  test/combinations.jl
Labels: documentation

#151 Standardization of combinations tests
  test/combinations.jl
  test/floating_point_types.jl
  test/runtests.jl
  test/utils.jl
Labels: testing, refactoring

#152 add AD (Enzyme) support via MeshIntegralsEnzymeExt
  .gitignore
  Project.toml
  benchmark/Project.toml
  benchmark/benchmarks.jl
  ext/MeshIntegralsEnzymeExt.jl
  src/MeshIntegrals.jl
  src/differentiation.jl
  src/integral.jl
  src/specializations/BezierCurve.jl
  src/specializations/CylinderSurface.jl
  src/utils.jl
  test/Project.toml
  test/combinations.jl
  test/floating_point_types.jl
  test/utils.jl
Labels: enhancement, dependencies

#159 Use more efficient parametric transformation for `Tetrahedron`
  src/specializations/Tetrahedron.jl
  src/specializations/Triangle.jl
Labels: refactoring

#158 Add a changelog
  CHANGELOG.md
  docs/make.jl
  docs/src/CHANGELOG.md
Labels: documentation

#160 Fix bug where integral fails when Enzyme ext not loaded
  CHANGELOG.md
  ext/MeshIntegralsEnzymeExt.jl
  src/utils.jl
  test/combinations.jl
  test/utils.jl
Labels: bug

#162 Add analytical unit tests for `Cylinder` and `CylinderSurface`
  CHANGELOG.md
  test/combinations.jl
Labels: testing
