Repository JuliaGeometry/MeshIntegrals.jl, pull requests merged in 2024-09, with the labels that each got.

#63 Push preview of documentation
  .github/workflows/DocPreviewCleanup.yml
  README.md
  docs/make.jl
  docs/src/algorithms.md
  docs/src/index.md
Labels: documentation

#78 Use TestItems.jl
  test/Project.toml
  test/aqua.jl
  test/auto_tests.jl
  test/combinations.jl
  test/floating_point_types.jl
  test/runtests.jl
Labels: testing

#85 Add downgrade action
  .github/workflows/Downgrade.yml
  Project.toml
  test/Project.toml
Labels: testing

#88 v0.14-DEV: Remove `derivative` and `unitdirection` from exports
  src/MeshIntegrals.jl
Labels: breaking

#90 Add test with ExplicitImports.jl
  src/MeshIntegrals.jl
  test/Project.toml
  test/aqua.jl
Labels: testing

#91 v0.14-DEV: Change `FP` to a keyword argument
  src/MeshIntegrals.jl
  src/differentiation.jl
  src/integral.jl
  src/integral_aliases.jl
  src/specializations/BezierCurve.jl
  src/specializations/ConeSurface.jl
  src/specializations/CylinderSurface.jl
  src/specializations/FrustumSurface.jl
  src/specializations/Line.jl
  src/specializations/Plane.jl
  src/specializations/Ray.jl
  src/specializations/Ring.jl
  src/specializations/Rope.jl
  src/specializations/Tetrahedron.jl
  src/specializations/Triangle.jl
  src/utils.jl
  test/floating_point_types.jl
Labels: breaking, refactoring

#92 Implement `differential` and `jacobian` for Bezier curve integrals
  docs/src/api.md
  src/differentiation.jl
  src/integral.jl
  src/specializations/BezierCurve.jl
  test/auto_tests.jl
  test/combinations.jl
Labels: refactoring

#95 Add tests for `Meshes.Quadrangle`
  docs/src/supportmatrix.md
  test/Project.toml
  test/combinations.jl
Labels: testing
