Repository JuliaGeometry/MeshIntegrals.jl, pull requests merged in 2024-10, with the labels that each got.

#100 Complete transition away from auto-tests
  test/auto_tests.jl
  test/combinations.jl
Labels: testing

#105 Add tests for `ParametrizedCurve`
  docs/src/supportmatrix.md
  test/Project.toml
  test/combinations.jl
Labels: testing

#109 Add an extended tag for time-intensive unit tests
  test/combinations.jl
  test/runtests.jl
Labels: enhancement, testing

#110 Add more analytic tests
  test/combinations.jl
  test/runtests.jl
Labels: testing

#117 Update links to reflect new JuliaGeometry ownership
  README.md
  docs/make.jl
  docs/src/index.md
  docs/src/supportmatrix.md
Labels: documentation

#119 Implement benchmarking with AirspeedVelocity.jl
  .github/workflows/AirspeedVelocity.yml
  benchmark/Project.toml
  benchmark/benchmarks.jl
Labels: enhancement

#123 Use `@autodocs` to dynamically include all docstrings
  docs/make.jl
  docs/src/api.md
  docs/src/supportmatrix.md
  src/integral_aliases.jl
  src/integration_rules.jl
  src/specializations/BezierCurve.jl
Labels: documentation
